//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int CId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> Def { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
