//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCCARDGRP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCCARDGRP()
        {
            this.DISCCARDS = new HashSet<DISCCARDS>();
        }
    
        public int GRPID { get; set; }
        public string NAME { get; set; }
        public int PID { get; set; }
        public int DISCTYPE { get; set; }
        public byte[] EXPIREDATE { get; set; }
        public Nullable<decimal> ONVALUE { get; set; }
        public int AUTONUM { get; set; }
        public string PREFIX { get; set; }
        public Nullable<int> CURRNUM { get; set; }
        public string SUFFIX { get; set; }
        public string NOTES { get; set; }
        public string GENNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCCARDS> DISCCARDS { get; set; }
    }
}
