//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.UserAccess = new HashSet<UserAccess>();
            this.UserTreeView = new HashSet<UserTreeView>();
        }
    
        public int FunId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> TabId { get; set; }
        public int Logging { get; set; }
        public int Flags { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual ICollection<UserAccess> UserAccess { get; set; }
        public virtual ICollection<UserTreeView> UserTreeView { get; set; }
    }
}
