//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAgentSaldo
    {
        public int KAId { get; set; }
        public System.DateTime OnDate { get; set; }
        public decimal Saldo { get; set; }
    
        public virtual Kagent Kagent { get; set; }
    }
}
