//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsList
    {
        public int MatId { get; set; }
        public Nullable<int> Num { get; set; }
        public string Produced { get; set; }
        public Nullable<decimal> NDS { get; set; }
        public Nullable<int> Serials { get; set; }
        public string Name { get; set; }
        public string Artikul { get; set; }
        public Nullable<int> WId { get; set; }
        public string MeasuresName { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> Archived { get; set; }
    }
}
