//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatGroup
    {
        public MatGroup()
        {
            this.KAMatGroupDiscount = new HashSet<KAMatGroupDiscount>();
            this.Materials = new HashSet<Materials>();
            this.MatGroupPrices = new HashSet<MatGroupPrices>();
        }
    
        public int GrpId { get; set; }
        public int PId { get; set; }
        public string Name { get; set; }
        public int Deleted { get; set; }
        public Nullable<decimal> Nds { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Num { get; set; }
    
        public virtual ICollection<KAMatGroupDiscount> KAMatGroupDiscount { get; set; }
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<MatGroupPrices> MatGroupPrices { get; set; }
    }
}
