//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatPrices
    {
        public int Id { get; set; }
        public int PTypeId { get; set; }
        public int MatId { get; set; }
        public decimal OnValue { get; set; }
        public Nullable<int> CurrId { get; set; }
        public int ExtraType { get; set; }
        public int Dis { get; set; }
        public Nullable<int> WithNds { get; set; }
        public Nullable<int> PPTypeId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual PriceTypes PriceTypes { get; set; }
        public virtual PriceTypes PriceTypes1 { get; set; }
    }
}
