//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatRecipe()
        {
            this.MatRecDet = new HashSet<MatRecDet>();
            this.WayBillMake = new HashSet<WayBillMake>();
        }
    
        public int RecId { get; set; }
        public string Num { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public int MatId { get; set; }
        public Nullable<int> RType { get; set; }
    
        public virtual Materials Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatRecDet> MatRecDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayBillMake> WayBillMake { get; set; }
    }
}
