//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintLog
    {
        public int PlId { get; set; }
        public Nullable<int> RepId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> PrintType { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
