//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAXES()
        {
            this.WayBillDetTaxes = new HashSet<WayBillDetTaxes>();
        }
    
        public int TAXID { get; set; }
        public string NAME { get; set; }
        public decimal ONVALUE { get; set; }
        public int TAXTYPE { get; set; }
        public int DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayBillDetTaxes> WayBillDetTaxes { get; set; }
    }
}
