//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PriceTypes
    {
        public int PTypeId { get; set; }
        public string Name { get; set; }
        public decimal OnValue { get; set; }
        public int Num { get; set; }
        public int Def { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> PPTypeId { get; set; }
        public Nullable<int> ExtraType { get; set; }
        public string PtName { get; set; }
        public string TypeName { get; set; }
    }
}
