//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PriceList
    {
        public int PlId { get; set; }
        public int CurrId { get; set; }
        public System.DateTime OnDate { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int Deleted { get; set; }
        public int UseLogo { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> PTypeId { get; set; }
        public string CurrName { get; set; }
    }
}
