//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKSPERSONS
    {
        public int PERSONID { get; set; }
        public int BANKID { get; set; }
        public string NAME { get; set; }
        public string JOB { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NOTES { get; set; }
    
        public virtual BANKS BANKS { get; set; }
    }
}
