//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTPARAMS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDR { get; set; }
        public string PHONE { get; set; }
        public string OKPO { get; set; }
        public string INN { get; set; }
        public string CERTNUM { get; set; }
        public string KPP { get; set; }
        public int NDSPAYER { get; set; }
        public string FULLNAME { get; set; }
    }
}
