//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMATGROUPDISCOUNT
    {
        public int DISCID { get; set; }
        public int KAID { get; set; }
        public int GRPID { get; set; }
        public decimal ONVALUE { get; set; }
    
        public virtual KAGENT KAGENT { get; set; }
        public virtual MATGROUP MATGROUP { get; set; }
    }
}
