//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATREMAINS
    {
        public int MATID { get; set; }
        public System.DateTime ONDATE { get; set; }
        public decimal REMAIN { get; set; }
        public decimal RSV { get; set; }
        public Nullable<decimal> AVGPRICE { get; set; }
        public Nullable<decimal> MINPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public Nullable<decimal> INWAY { get; set; }
        public Nullable<decimal> ORDERED { get; set; }
        public Nullable<decimal> ORSV { get; set; }
    
        public virtual MATERIALS MATERIALS { get; set; }
    }
}
