//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNREL
    {
        public int POSID { get; set; }
        public int OUTPOSID { get; set; }
        public int PPOSID { get; set; }
        public Nullable<int> DPOSID { get; set; }
    
        public virtual WaybillDet WaybillDet { get; set; }
        public virtual WaybillDet WaybillDet1 { get; set; }
        public virtual WaybillDet WaybillDet2 { get; set; }
        public virtual WaybillDet WaybillDet3 { get; set; }
    }
}
