//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Saklad.SpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVCGROUP
    {
        public SVCGROUP()
        {
            this.SERVICES = new HashSet<SERVICES>();
        }
    
        public int GRPID { get; set; }
        public int PID { get; set; }
        public string NAME { get; set; }
        public int DELETED { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> NUM { get; set; }
    
        public virtual ICollection<SERVICES> SERVICES { get; set; }
    }
}
