//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKS
    {
        public BANKS()
        {
            this.BANKSPERSONS = new HashSet<BANKSPERSONS>();
            this.KAgentAccount = new HashSet<KAgentAccount>();
        }
    
        public int BANKID { get; set; }
        public string MFO { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string WWW { get; set; }
        public string CORACC { get; set; }
        public int DEF { get; set; }
        public int DELETED { get; set; }
    
        public virtual ICollection<BANKSPERSONS> BANKSPERSONS { get; set; }
        public virtual ICollection<KAgentAccount> KAgentAccount { get; set; }
    }
}
