//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Routes = new HashSet<Routes>();
            this.Expedition = new HashSet<Expedition>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<decimal> СarryingСapacity { get; set; }
        public string WIN { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual ICollection<Routes> Routes { get; set; }
        public virtual Kagent Kagent { get; set; }
        public virtual ICollection<Expedition> Expedition { get; set; }
    }
}
