//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMISSION
    {
        public int ID { get; set; }
        public int WBILLID { get; set; }
        public int KAID { get; set; }
        public Nullable<int> FIRST_KAID { get; set; }
        public Nullable<int> SECOND_KAID { get; set; }
        public Nullable<int> THIRD_KAID { get; set; }
    
        public virtual WaybillList WaybillList { get; set; }
        public virtual Kagent Kagent { get; set; }
        public virtual Kagent Kagent1 { get; set; }
        public virtual Kagent Kagent2 { get; set; }
        public virtual Kagent Kagent3 { get; set; }
    }
}
