//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int Id { get; set; }
        public int WbillId { get; set; }
        public Nullable<int> KaId { get; set; }
        public Nullable<int> FirstKaId { get; set; }
        public Nullable<int> SecondKaId { get; set; }
        public Nullable<int> ThirdKaId { get; set; }
    
        public virtual WaybillList WaybillList { get; set; }
        public virtual Kagent Kagent { get; set; }
        public virtual Kagent Kagent1 { get; set; }
        public virtual Kagent Kagent2 { get; set; }
        public virtual Kagent Kagent3 { get; set; }
    }
}
