//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonParams
    {
        public int Id { get; set; }
        public Nullable<decimal> Nds { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<int> PoType { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> DelToBin { get; set; }
        public string Ver { get; set; }
        public string TemplatePatch { get; set; }
        public Nullable<System.DateTime> EndCalcPeriod { get; set; }
        public Nullable<System.DateTime> TrialPeriod { get; set; }
    }
}
