//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int CId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> Def { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
