//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRIES
    {
        public COUNTRIES()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int CID { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public int DELETED { get; set; }
        public Nullable<int> DEF { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
