//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCYRATE
    {
        public int CURRID { get; set; }
        public System.DateTime ONDATE { get; set; }
        public decimal ONVALUE { get; set; }
        public int RATEID { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
    }
}
