//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public int RateId { get; set; }
        public int CurrId { get; set; }
        public System.DateTime OnDate { get; set; }
        public decimal OnValue { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
