//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docs
    {
        public Docs()
        {
            this.CONTRACTS = new HashSet<CONTRACTS>();
            this.CONTRACTS1 = new HashSet<CONTRACTS>();
            this.DocsRel = new HashSet<DocsRel>();
            this.PayDoc = new HashSet<PayDoc>();
            this.TAXWB = new HashSet<TAXWB>();
            this.WaybillList = new HashSet<WaybillList>();
            this.PriceList = new HashSet<PriceList>();
        }
    
        public int DocId { get; set; }
        public int DocType { get; set; }
    
        public virtual ICollection<CONTRACTS> CONTRACTS { get; set; }
        public virtual ICollection<CONTRACTS> CONTRACTS1 { get; set; }
        public virtual ICollection<DocsRel> DocsRel { get; set; }
        public virtual ICollection<PayDoc> PayDoc { get; set; }
        public virtual ICollection<TAXWB> TAXWB { get; set; }
        public virtual ICollection<WaybillList> WaybillList { get; set; }
        public virtual ICollection<PriceList> PriceList { get; set; }
    }
}
