//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTPARAMS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDR { get; set; }
        public string PHONE { get; set; }
        public string OKPO { get; set; }
        public string INN { get; set; }
        public string CERTNUM { get; set; }
        public string KPP { get; set; }
        public int NDSPAYER { get; set; }
        public string FULLNAME { get; set; }
    }
}
