//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtRel
    {
        public int Id { get; set; }
        public int IntPosId { get; set; }
        public int ExtPosId { get; set; }
    
        public virtual WaybillDet WaybillDet { get; set; }
        public virtual WaybillDet WaybillDet1 { get; set; }
    }
}
