//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.UserAccess = new HashSet<UserAccess>();
            this.UserTreeView = new HashSet<UserTreeView>();
        }
    
        public int FunId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> TabId { get; set; }
        public int Logging { get; set; }
        public int Flags { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual ICollection<UserAccess> UserAccess { get; set; }
        public virtual ICollection<UserTreeView> UserTreeView { get; set; }
    }
}
