//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAADDR
    {
        public int ADDRID { get; set; }
        public int KAID { get; set; }
        public int ADDRTYPE { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string ADDRESS { get; set; }
        public string POSTINDEX { get; set; }
        public string REGION { get; set; }
        public Nullable<int> CITYTYPE { get; set; }
    
        public virtual KAGENT KAGENT { get; set; }
    }
}
