//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KADISCOUNT
    {
        public int KAID { get; set; }
        public int DISCFORALL { get; set; }
        public decimal ONVALUE { get; set; }
        public int DISCCUSTOM { get; set; }
    
        public virtual KAGENT KAGENT { get; set; }
    }
}
