//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kagent
    {
        public Kagent()
        {
            this.COMMISSION = new HashSet<COMMISSION>();
            this.COMMISSION1 = new HashSet<COMMISSION>();
            this.COMMISSION2 = new HashSet<COMMISSION>();
            this.COMMISSION3 = new HashSet<COMMISSION>();
            this.CONTRACTS = new HashSet<CONTRACTS>();
            this.CONTRACTS1 = new HashSet<CONTRACTS>();
            this.DISCCARDS = new HashSet<DISCCARDS>();
            this.KAADDR = new HashSet<KAADDR>();
            this.KAMATDISCOUNT = new HashSet<KAMATDISCOUNT>();
            this.KAMATGROUPDISCOUNT = new HashSet<KAMATGROUPDISCOUNT>();
            this.TAXWB = new HashSet<TAXWB>();
            this.WaybillList = new HashSet<WaybillList>();
            this.WAYBILLMOVE = new HashSet<WAYBILLMOVE>();
            this.KAGENTACCOUNT = new HashSet<KAGENTACCOUNT>();
            this.KAGENTDOC = new HashSet<KAGENTDOC>();
            this.KAGENTPERSONS = new HashSet<KAGENTPERSONS>();
            this.TAXWB1 = new HashSet<TAXWB>();
            this.TECHPROCDET = new HashSet<TECHPROCDET>();
            this.WaybillList1 = new HashSet<WaybillList>();
            this.WAYBILLMAKE = new HashSet<WAYBILLMAKE>();
            this.WaybillList2 = new HashSet<WaybillList>();
            this.WAYBILLSVC = new HashSet<WAYBILLSVC>();
            this.PayDoc = new HashSet<PayDoc>();
            this.PayDoc1 = new HashSet<PayDoc>();
            this.KAgentSaldo = new HashSet<KAgentSaldo>();
        }
    
        public int KaId { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string INN { get; set; }
        public string OKPO { get; set; }
        public string CertNum { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string www { get; set; }
        public string Fax { get; set; }
        public int Deleted { get; set; }
        public string Notes { get; set; }
        public string KPP { get; set; }
        public int NdsPayer { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int KType { get; set; }
        public int KaKind { get; set; }
        public string Job { get; set; }
        public Nullable<decimal> StartSaldo { get; set; }
        public Nullable<System.DateTime> StartSaldoDate { get; set; }
        public Nullable<int> PTypeId { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<int> Def { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Archived { get; set; }
        public string KAU { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractNum { get; set; }
    
        public virtual ICollection<COMMISSION> COMMISSION { get; set; }
        public virtual ICollection<COMMISSION> COMMISSION1 { get; set; }
        public virtual ICollection<COMMISSION> COMMISSION2 { get; set; }
        public virtual ICollection<COMMISSION> COMMISSION3 { get; set; }
        public virtual ICollection<CONTRACTS> CONTRACTS { get; set; }
        public virtual ICollection<CONTRACTS> CONTRACTS1 { get; set; }
        public virtual ICollection<DISCCARDS> DISCCARDS { get; set; }
        public virtual ICollection<KAADDR> KAADDR { get; set; }
        public virtual KADISCOUNT KADISCOUNT { get; set; }
        public virtual ICollection<KAMATDISCOUNT> KAMATDISCOUNT { get; set; }
        public virtual ICollection<KAMATGROUPDISCOUNT> KAMATGROUPDISCOUNT { get; set; }
        public virtual ICollection<TAXWB> TAXWB { get; set; }
        public virtual ICollection<WaybillList> WaybillList { get; set; }
        public virtual ICollection<WAYBILLMOVE> WAYBILLMOVE { get; set; }
        public virtual ICollection<KAGENTACCOUNT> KAGENTACCOUNT { get; set; }
        public virtual ICollection<KAGENTDOC> KAGENTDOC { get; set; }
        public virtual ICollection<KAGENTPERSONS> KAGENTPERSONS { get; set; }
        public virtual ICollection<TAXWB> TAXWB1 { get; set; }
        public virtual ICollection<TECHPROCDET> TECHPROCDET { get; set; }
        public virtual ICollection<WaybillList> WaybillList1 { get; set; }
        public virtual ICollection<WAYBILLMAKE> WAYBILLMAKE { get; set; }
        public virtual ICollection<WaybillList> WaybillList2 { get; set; }
        public virtual ICollection<WAYBILLSVC> WAYBILLSVC { get; set; }
        public virtual ICollection<PayDoc> PayDoc { get; set; }
        public virtual ICollection<PayDoc> PayDoc1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<KAgentSaldo> KAgentSaldo { get; set; }
    }
}
