//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAgentMatPrices
    {
        public int KaId { get; set; }
        public int MatId { get; set; }
        public decimal OnValue { get; set; }
        public int PricingType { get; set; }
        public int ValueType { get; set; }
        public int PTypeId { get; set; }
    
        public virtual Kagent Kagent { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual PriceTypes PriceTypes { get; set; }
    }
}
