//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAgentDoc
    {
        public int KAId { get; set; }
        public string DocName { get; set; }
        public string DocNum { get; set; }
        public string DocSeries { get; set; }
        public string DocWhoProduce { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    
        public virtual Kagent Kagent { get; set; }
    }
}
