//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAgentAdjustmentDet
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Idx { get; set; }
        public Nullable<System.Guid> KAgentAdjustmentId { get; set; }
        public Nullable<System.Guid> DocId { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual KAgentAdjustment KAgentAdjustment { get; set; }
    }
}
