//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAgentAdjustment
    {
        public KAgentAdjustment()
        {
            this.KAgentAdjustmentDet = new HashSet<KAgentAdjustmentDet>();
        }
    
        public System.Guid Id { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> DebtKaId { get; set; }
        public Nullable<int> CreditKaId { get; set; }
        public string Reason { get; set; }
        public int Checked { get; set; }
        public int Deleted { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CurrId { get; set; }
        public Nullable<decimal> OnValue { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public int WriteOffType { get; set; }
        public int OperationType { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public int WType { get; set; }
    
        public virtual OperationTypes OperationTypes { get; set; }
        public virtual WriteOffTypes WriteOffTypes { get; set; }
        public virtual ICollection<KAgentAdjustmentDet> KAgentAdjustmentDet { get; set; }
        public virtual Kagent Kagent { get; set; }
        public virtual Kagent Kagent1 { get; set; }
        public virtual Kagent Kagent2 { get; set; }
    }
}
