//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMatGroupDiscount
    {
        public System.Guid DiscId { get; set; }
        public int KAId { get; set; }
        public int GrpId { get; set; }
        public decimal OnValue { get; set; }
    
        public virtual MatGroup MatGroup { get; set; }
        public virtual Kagent Kagent { get; set; }
    }
}
