//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string MachineName { get; set; }
        public string UserName { get; set; }
        public string Ver { get; set; }
    }
}
