//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatChange
    {
        public int MatId { get; set; }
        public int ChangeId { get; set; }
        public string Notes { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Materials Materials1 { get; set; }
    }
}
