//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATGROUP
    {
        public MATGROUP()
        {
            this.KAMATGROUPDISCOUNT = new HashSet<KAMATGROUPDISCOUNT>();
            this.MATERIALS = new HashSet<MATERIALS>();
            this.MATERIALS1 = new HashSet<MATERIALS>();
            this.MATERIALS2 = new HashSet<MATERIALS>();
            this.MATGROUPPRICES = new HashSet<MATGROUPPRICES>();
        }
    
        public int GRPID { get; set; }
        public int PID { get; set; }
        public string NAME { get; set; }
        public int DELETED { get; set; }
        public Nullable<decimal> NDS { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> NUM { get; set; }
    
        public virtual ICollection<KAMATGROUPDISCOUNT> KAMATGROUPDISCOUNT { get; set; }
        public virtual ICollection<MATERIALS> MATERIALS { get; set; }
        public virtual ICollection<MATERIALS> MATERIALS1 { get; set; }
        public virtual ICollection<MATERIALS> MATERIALS2 { get; set; }
        public virtual ICollection<MATGROUPPRICES> MATGROUPPRICES { get; set; }
    }
}
