//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatPrices
    {
        public int Id { get; set; }
        public int PTypeId { get; set; }
        public int MatId { get; set; }
        public decimal OnValue { get; set; }
        public Nullable<int> CurrId { get; set; }
        public int ExtraType { get; set; }
        public int Dis { get; set; }
        public Nullable<int> WithNds { get; set; }
        public Nullable<int> PPTypeId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual PriceTypes PriceTypes { get; set; }
        public virtual PriceTypes PriceTypes1 { get; set; }
    }
}
