//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatRecipeTechProcDet
    {
        public int Id { get; set; }
        public int RecId { get; set; }
        public int ProcId { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<decimal> ExpectedOut { get; set; }
    
        public virtual MatRecipe MatRecipe { get; set; }
        public virtual TechProcess TechProcess { get; set; }
    }
}
