//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measures
    {
        public Measures()
        {
            this.Materials = new HashSet<Materials>();
            this.Services = new HashSet<Services>();
            this.MaterialMeasures = new HashSet<MaterialMeasures>();
            this.MatRecipe = new HashSet<MatRecipe>();
        }
    
        public int MId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Def { get; set; }
        public int Deleted { get; set; }
        public string Code { get; set; }
        public bool AutoCalcRecipe { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<Services> Services { get; set; }
        public virtual ICollection<MaterialMeasures> MaterialMeasures { get; set; }
        public virtual ICollection<MatRecipe> MatRecipe { get; set; }
    }
}
