//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYDOC
    {
        public int PAYDOCID { get; set; }
        public int DOCTYPE { get; set; }
        public System.DateTime ONDATE { get; set; }
        public Nullable<int> KAID { get; set; }
        public decimal TOTAL { get; set; }
        public int PTYPEID { get; set; }
        public int CURRID { get; set; }
        public int DELETED { get; set; }
        public string DOCNUM { get; set; }
        public int CHECKED { get; set; }
        public int WITHNDS { get; set; }
        public string REASON { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> MPERSONID { get; set; }
        public int CTYPEID { get; set; }
        public Nullable<int> ACCID { get; set; }
        public Nullable<int> CASHID { get; set; }
        public Nullable<int> OPERID { get; set; }
        public Nullable<int> DOCID { get; set; }
        public Nullable<decimal> ONVALUE { get; set; }
        public string SCHET { get; set; }
    
        public virtual CASHDESKS CASHDESKS { get; set; }
        public virtual CHARGETYPE CHARGETYPE { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DOCS DOCS { get; set; }
        public virtual KAGENT KAGENT { get; set; }
        public virtual KAGENT KAGENT1 { get; set; }
        public virtual KAGENT KAGENT2 { get; set; }
        public virtual KAGENTACCOUNT KAGENTACCOUNT { get; set; }
        public virtual PAYTYPE PAYTYPE { get; set; }
    }
}
