//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSREMAINS
    {
        public int POSID { get; set; }
        public int WID { get; set; }
        public int MATID { get; set; }
        public System.DateTime ONDATE { get; set; }
        public decimal REMAIN { get; set; }
        public decimal RSV { get; set; }
        public Nullable<decimal> AVGPRICE { get; set; }
        public Nullable<decimal> INWAY { get; set; }
        public Nullable<decimal> ORDERED { get; set; }
    
        public virtual MATERIALS MATERIALS { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual WaybillDet WaybillDet { get; set; }
    }
}
