//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListDet
    {
        public int PlDetId { get; set; }
        public Nullable<int> MatId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int PlId { get; set; }
        public Nullable<int> GrpId { get; set; }
        public Nullable<int> PlDetType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual PriceList PriceList { get; set; }
    }
}
