//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICETYPES
    {
        public PRICETYPES()
        {
            this.MATGROUPPRICES = new HashSet<MATGROUPPRICES>();
            this.MATGROUPPRICES1 = new HashSet<MATGROUPPRICES>();
            this.MATPRICES = new HashSet<MATPRICES>();
            this.MATPRICES1 = new HashSet<MATPRICES>();
            this.PRICELIST = new HashSet<PRICELIST>();
            this.WaybillDet = new HashSet<WaybillDet>();
        }
    
        public int PTYPEID { get; set; }
        public string NAME { get; set; }
        public decimal ONVALUE { get; set; }
        public int NUM { get; set; }
        public int DEF { get; set; }
        public int DELETED { get; set; }
        public Nullable<int> PPTYPEID { get; set; }
        public Nullable<int> EXTRATYPE { get; set; }
    
        public virtual ICollection<MATGROUPPRICES> MATGROUPPRICES { get; set; }
        public virtual ICollection<MATGROUPPRICES> MATGROUPPRICES1 { get; set; }
        public virtual ICollection<MATPRICES> MATPRICES { get; set; }
        public virtual ICollection<MATPRICES> MATPRICES1 { get; set; }
        public virtual ICollection<PRICELIST> PRICELIST { get; set; }
        public virtual ICollection<WaybillDet> WaybillDet { get; set; }
    }
}
