//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTypes
    {
        public PriceTypes()
        {
            this.MATGROUPPRICES = new HashSet<MATGROUPPRICES>();
            this.MATGROUPPRICES1 = new HashSet<MATGROUPPRICES>();
            this.MATPRICES = new HashSet<MATPRICES>();
            this.MATPRICES1 = new HashSet<MATPRICES>();
            this.PRICELIST = new HashSet<PRICELIST>();
            this.WaybillDet = new HashSet<WaybillDet>();
        }
    
        public int PTypeId { get; set; }
        public string Name { get; set; }
        public decimal OnValue { get; set; }
        public int Num { get; set; }
        public int Def { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> PPTypeId { get; set; }
        public Nullable<int> ExtraType { get; set; }
    
        public virtual ICollection<MATGROUPPRICES> MATGROUPPRICES { get; set; }
        public virtual ICollection<MATGROUPPRICES> MATGROUPPRICES1 { get; set; }
        public virtual ICollection<MATPRICES> MATPRICES { get; set; }
        public virtual ICollection<MATPRICES> MATPRICES1 { get; set; }
        public virtual ICollection<PRICELIST> PRICELIST { get; set; }
        public virtual ICollection<WaybillDet> WaybillDet { get; set; }
    }
}
