//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public PriceList()
        {
            this.PriceListDet = new HashSet<PriceListDet>();
            this.PlannedCalculation = new HashSet<PlannedCalculation>();
            this.Kagent = new HashSet<Kagent>();
        }
    
        public int PlId { get; set; }
        public int CurrId { get; set; }
        public System.DateTime OnDate { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int Deleted { get; set; }
        public int UseLogo { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> PTypeId { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual PriceTypes PriceTypes { get; set; }
        public virtual ICollection<PriceListDet> PriceListDet { get; set; }
        public virtual ICollection<PlannedCalculation> PlannedCalculation { get; set; }
        public virtual ICollection<Kagent> Kagent { get; set; }
    }
}
