//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTypes
    {
        public PriceTypes()
        {
            this.MatGroupPrices = new HashSet<MatGroupPrices>();
            this.MatGroupPrices1 = new HashSet<MatGroupPrices>();
            this.MatPrices = new HashSet<MatPrices>();
            this.MatPrices1 = new HashSet<MatPrices>();
            this.WaybillDet = new HashSet<WaybillDet>();
            this.PriceList = new HashSet<PriceList>();
        }
    
        public int PTypeId { get; set; }
        public string Name { get; set; }
        public decimal OnValue { get; set; }
        public int Num { get; set; }
        public int Def { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> PPTypeId { get; set; }
        public Nullable<int> ExtraType { get; set; }
    
        public virtual ICollection<MatGroupPrices> MatGroupPrices { get; set; }
        public virtual ICollection<MatGroupPrices> MatGroupPrices1 { get; set; }
        public virtual ICollection<MatPrices> MatPrices { get; set; }
        public virtual ICollection<MatPrices> MatPrices1 { get; set; }
        public virtual ICollection<WaybillDet> WaybillDet { get; set; }
        public virtual ICollection<PriceList> PriceList { get; set; }
    }
}
