//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintLog
    {
        public int PlId { get; set; }
        public Nullable<int> RepId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<System.Guid> OriginatorId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
