//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINTLOG
    {
        public int PLID { get; set; }
        public Nullable<int> REPID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> ONDATE { get; set; }
        public Nullable<int> PRINTTYPE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
