//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectManagement
    {
        public ProjectManagement()
        {
            this.ProjectManagementDet = new HashSet<ProjectManagementDet>();
        }
    
        public System.Guid Id { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public int DocType { get; set; }
        public string Reason { get; set; }
        public int Checked { get; set; }
        public int Deleted { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CurrId { get; set; }
        public Nullable<decimal> OnValue { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public Nullable<int> KaId { get; set; }
        public int EntId { get; set; }
    
        public virtual ICollection<ProjectManagementDet> ProjectManagementDet { get; set; }
    }
}
