//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialManagement
    {
        public RawMaterialManagement()
        {
            this.RawMaterialManagementDet = new HashSet<RawMaterialManagementDet>();
        }
    
        public System.Guid Id { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> WId { get; set; }
        public int Checked { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int DocType { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> KaId { get; set; }
    
        public virtual ICollection<RawMaterialManagementDet> RawMaterialManagementDet { get; set; }
    }
}
