//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public System.Guid Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalSum { get; set; }
        public Nullable<int> TotalPayment { get; set; }
        public Nullable<System.DateTime> CeatedAt { get; set; }
        public Nullable<System.Guid> ShiftId { get; set; }
    }
}
