//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSortedFields
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Idx { get; set; }
        public string FieldName { get; set; }
        public string Caption { get; set; }
        public Nullable<int> OrderDirection { get; set; }
        public Nullable<int> RepId { get; set; }
    }
}
