//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTS
    {
        public REPORTS()
        {
            this.REPLNG = new HashSet<REPLNG>();
        }
    
        public int REPID { get; set; }
        public int GRPID { get; set; }
        public int FIL { get; set; }
        public Nullable<int> NUM { get; set; }
    
        public virtual ICollection<REPLNG> REPLNG { get; set; }
    }
}
