//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.Kagent = new HashSet<Kagent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DriverId { get; set; }
    
        public virtual ICollection<Kagent> Kagent { get; set; }
        public virtual Kagent Kagent1 { get; set; }
    }
}
