//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulingOrders
    {
        public System.Guid Id { get; set; }
        public int RecId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual MatRecipe MatRecipe { get; set; }
    }
}
