//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcGroup
    {
        public SvcGroup()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int GrpId { get; set; }
        public int PId { get; set; }
        public string Name { get; set; }
        public int Deleted { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual ICollection<Services> Services { get; set; }
    }
}
