//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        public Tables()
        {
            this.OperLog = new HashSet<OperLog>();
            this.Functions = new HashSet<Functions>();
        }
    
        public int TabId { get; set; }
        public string TableName { get; set; }
        public string KeyName { get; set; }
    
        public virtual ICollection<OperLog> OperLog { get; set; }
        public virtual ICollection<Functions> Functions { get; set; }
    }
}
