//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLES
    {
        public TABLES()
        {
            this.FUNCTIONS = new HashSet<FUNCTIONS>();
            this.OPERLOG = new HashSet<OPERLOG>();
        }
    
        public int TABID { get; set; }
        public string TABLENAME { get; set; }
        public string KEYNAME { get; set; }
    
        public virtual ICollection<FUNCTIONS> FUNCTIONS { get; set; }
        public virtual ICollection<OPERLOG> OPERLOG { get; set; }
    }
}
