//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXWBDET
    {
        public int TWBDETID { get; set; }
        public int TWBID { get; set; }
        public int MATID { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime ONDATE { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<decimal> NDS { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual TAXWB TAXWB { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
