//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechProcess
    {
        public TechProcess()
        {
            this.MatRecipeTechProcDet = new HashSet<MatRecipeTechProcDet>();
            this.TechProcDet = new HashSet<TechProcDet>();
        }
    
        public int ProcId { get; set; }
        public string Name { get; set; }
        public string Kod { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual ICollection<MatRecipeTechProcDet> MatRecipeTechProcDet { get; set; }
        public virtual ICollection<TechProcDet> TechProcDet { get; set; }
    }
}
