//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTree
    {
        public UserTree()
        {
            this.UserTreeView = new HashSet<UserTreeView>();
        }
    
        public int TreeId { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<UserTreeView> UserTreeView { get; set; }
    }
}
