//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessCashDesks
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public int CashId { get; set; }
        public int Def { get; set; }
    
        public virtual CashDesks CashDesks { get; set; }
        public virtual Users Users { get; set; }
    }
}
