//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTreeAccess
    {
        public int Id { get; set; }
        public Nullable<int> FunId { get; set; }
        public int PId { get; set; }
        public int Num { get; set; }
        public Nullable<int> ImageIndex { get; set; }
        public int IsGroup { get; set; }
        public Nullable<int> ShowInTree { get; set; }
        public Nullable<int> GType { get; set; }
        public Nullable<int> DisabledIndex { get; set; }
        public int ShowExpanded { get; set; }
        public string Name { get; set; }
        public Nullable<int> CanView { get; set; }
        public Nullable<int> CanInsert { get; set; }
        public Nullable<int> CanModify { get; set; }
        public Nullable<int> CanDelete { get; set; }
        public Nullable<int> CanPost { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WType { get; set; }
    }
}
