//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FunId { get; set; }
        public int CanView { get; set; }
        public int CanInsert { get; set; }
        public int CanModify { get; set; }
        public int CanDelete { get; set; }
        public int CanPost { get; set; }
    
        public virtual Functions Functions { get; set; }
        public virtual Users Users { get; set; }
    }
}
