//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Actives
    {
        public System.DateTime OnDate { get; set; }
        public Nullable<decimal> WhSumm { get; set; }
        public Nullable<decimal> Creditors { get; set; }
        public Nullable<decimal> Debitors { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> CashLess { get; set; }
        public Nullable<decimal> Active { get; set; }
    }
}
