//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BankStatementsDet
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BankStatementId { get; set; }
        public string FOP { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string EGRPOU { get; set; }
        public string MFO { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> PaySum { get; set; }
        public string Reason { get; set; }
        public string KagentName { get; set; }
        public Nullable<int> Checked { get; set; }
        public string BankName { get; set; }
        public string DocNum { get; set; }
        public string ChargeTypeName { get; set; }
    }
}
