//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DeboningDet
    {
        public int DebId { get; set; }
        public int WBillId { get; set; }
        public int MatId { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public int WId { get; set; }
        public string MatName { get; set; }
        public string WhName { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalWeighing { get; set; }
        public string MsrName { get; set; }
    }
}
