//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DiscCards
    {
        public int CardId { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public decimal OnValue { get; set; }
        public string KaName { get; set; }
        public string KaFullName { get; set; }
        public string GrpName { get; set; }
        public int GrpId { get; set; }
    }
}
