//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ExpeditionWBMaterialsDet
    {
        public int MatId { get; set; }
        public string Name { get; set; }
        public string Artikul { get; set; }
        public int WbillId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.Guid Id { get; set; }
        public int PosId { get; set; }
        public Nullable<System.Guid> ExpeditionMaterialsDetId { get; set; }
    }
}
