//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IntermediateWeighingDet
    {
        public System.Guid Id { get; set; }
        public string MatName { get; set; }
        public decimal Amount { get; set; }
        public int MatId { get; set; }
        public System.Guid IntermediateWeighingId { get; set; }
        public string MsrName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public int Checked { get; set; }
        public string PersonName { get; set; }
        public int WbillId { get; set; }
        public Nullable<decimal> TaraAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string VizokName { get; set; }
        public Nullable<decimal> VizokWeight { get; set; }
    }
}
