//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IntermediateWeighingSummary
    {
        public int WbillId { get; set; }
        public int MatId { get; set; }
        public System.Guid IntermediateWeighingId { get; set; }
        public Nullable<System.Guid> IntermediateWeighingDetId { get; set; }
        public string MatName { get; set; }
        public System.DateTime WbOnDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Checked { get; set; }
        public string RecipeName { get; set; }
        public string WbNum { get; set; }
        public string IntermediateWeighingNum { get; set; }
        public Nullable<decimal> IntermediateWeighingAmount { get; set; }
        public string MsrName { get; set; }
        public Nullable<int> RecipeCount { get; set; }
        public int RecipeGrpId { get; set; }
        public string GroupName { get; set; }
        public string ReceipeMsrName { get; set; }
        public Nullable<int> GrpId { get; set; }
        public int UserId { get; set; }
        public byte[] BMP { get; set; }
        public System.DateTime OnDate { get; set; }
        public int RecipeMatId { get; set; }
        public Nullable<decimal> AmountByRecipe { get; set; }
        public Nullable<decimal> TotalWeightByRecipe { get; set; }
        public Nullable<decimal> AmountIntermediateWeighing { get; set; }
        public Nullable<int> RecId { get; set; }
    }
}
