//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_KAgentPrices
    {
        public int EntityTyp { get; set; }
        public int EntityId { get; set; }
        public decimal OnValue { get; set; }
        public int PricingType { get; set; }
        public int ValueType { get; set; }
        public int PTypeId { get; set; }
        public int KaId { get; set; }
        public string Name { get; set; }
        public string PriceTypeName { get; set; }
        public System.Guid Id { get; set; }
    }
}
