//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_KAgentDocs
    {
        public System.Guid Id { get; set; }
        public Nullable<int> WType { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> KaId { get; set; }
        public string Name { get; set; }
        public int Checked { get; set; }
        public Nullable<decimal> Nds { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> OnValue { get; set; }
        public Nullable<int> CurrId { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> SummPay { get; set; }
        public string DocShortName { get; set; }
        public string DocTypeName { get; set; }
    }
}
