//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MatRecipe
    {
        public int RecId { get; set; }
        public string MatName { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public decimal Amount { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string GrpName { get; set; }
        public decimal Out { get; set; }
        public Nullable<int> RType { get; set; }
        public bool Archived { get; set; }
        public int GrpId { get; set; }
        public Nullable<decimal> Num { get; set; }
    }
}
