//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ProjectManagementDet
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<System.Guid> ProjectManagementId { get; set; }
        public Nullable<System.Guid> DocId { get; set; }
        public Nullable<int> WType { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public Nullable<decimal> SummPay { get; set; }
        public Nullable<decimal> OnValue { get; set; }
        public string CurrName { get; set; }
        public string DocShortName { get; set; }
        public string DocTypeName { get; set; }
        public string Notes { get; set; }
    }
}
