//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PriceTypes
    {
        public int PTypeId { get; set; }
        public string Name { get; set; }
        public decimal OnValue { get; set; }
        public int Num { get; set; }
        public int Def { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> PPTypeId { get; set; }
        public Nullable<int> ExtraType { get; set; }
        public string PtName { get; set; }
        public string TypeName { get; set; }
    }
}
