//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SettingMaterialPricesDet
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int MatId { get; set; }
        public decimal Price { get; set; }
        public System.Guid SettingMaterialPricesId { get; set; }
        public string MatName { get; set; }
        public string GrpName { get; set; }
        public Nullable<int> GrpId { get; set; }
        public System.DateTime OnDate { get; set; }
        public int Checked { get; set; }
        public string Artikul { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<int> Num { get; set; }
        public string MsrName { get; set; }
        public Nullable<decimal> ProcurementPrice { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> LastProcurementPrice { get; set; }
    }
}
