//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Users
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public string FullName { get; set; }
        public string SysName { get; set; }
        public Nullable<int> ShowBalance { get; set; }
        public Nullable<int> ShowPrice { get; set; }
        public Nullable<int> EnableEditDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string ReportFormat { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<bool> InternalEditor { get; set; }
        public string EmployeeName { get; set; }
    }
}
