//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Users
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public string FullName { get; set; }
        public string SysName { get; set; }
        public Nullable<int> ShowBalance { get; set; }
        public Nullable<int> ShowPrice { get; set; }
        public Nullable<int> EnableEditDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string ReportFormat { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<bool> InternalEditor { get; set; }
        public bool IsWorking { get; set; }
        public string EmployeeName { get; set; }
    }
}
