//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WaybillList
    {
        public int WbillId { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> CurrId { get; set; }
        public string Reason { get; set; }
        public int Checked { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public int WType { get; set; }
        public Nullable<decimal> Nds { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<decimal> SummPay { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> OnValue { get; set; }
        public string Name { get; set; }
        public Nullable<int> KaId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string PersonName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostIndex { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string www { get; set; }
        public Nullable<int> KType { get; set; }
        public string AttNum { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string Received { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int DefNum { get; set; }
        public Nullable<int> EntId { get; set; }
        public string WhName { get; set; }
        public string DestWhName { get; set; }
        public string KAU { get; set; }
        public string MovPersonName { get; set; }
        public string CType { get; set; }
        public string EntKaFullName { get; set; }
        public string EntKaPhone { get; set; }
        public string EntAddress { get; set; }
        public string EntCity { get; set; }
        public string EntDistrict { get; set; }
        public string EntRegion { get; set; }
        public string EntPostIndex { get; set; }
        public string EntINN { get; set; }
        public string EntCertNum { get; set; }
        public string EntCType { get; set; }
        public string AddressSel { get; set; }
        public string AddressBuy { get; set; }
        public string EntOKPO { get; set; }
        public System.Guid Id { get; set; }
        public string Declaration { get; set; }
        public string CarNumber { get; set; }
        public string CarName { get; set; }
        public Nullable<decimal> Balans { get; set; }
        public string DriverName { get; set; }
    }
}
