//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WaybillTemplateDet
    {
        public Nullable<int> Num { get; set; }
        public string MatName { get; set; }
        public string GrpName { get; set; }
        public Nullable<decimal> GrpNum { get; set; }
        public string Artikul { get; set; }
        public System.Guid WaybillTemplateId { get; set; }
        public System.Guid Id { get; set; }
        public int MatId { get; set; }
        public string MsrName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WId { get; set; }
    }
}
