//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WaybillMove
    {
        public System.Guid Id { get; set; }
        public int WbillId { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> CurrId { get; set; }
        public string Reason { get; set; }
        public int Checked { get; set; }
        public Nullable<decimal> SummAll { get; set; }
        public int WType { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<decimal> SummPay { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> SummInCurr { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> EntId { get; set; }
        public string EntName { get; set; }
        public string DocTypeName { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedUserName { get; set; }
        public int Deleted { get; set; }
        public string AttNum { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<decimal> DefTotalAmount { get; set; }
        public Nullable<decimal> ExTotalAmount { get; set; }
        public int FromWId { get; set; }
        public string FromWh { get; set; }
        public Nullable<int> ToWId { get; set; }
        public string ToWh { get; set; }
    }
}
