//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WhPosRemains
    {
        public int Id { get; set; }
        public int PosId { get; set; }
        public int WId { get; set; }
        public int MatId { get; set; }
        public decimal Remain { get; set; }
        public decimal Rsv { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public decimal Ordered { get; set; }
        public decimal OrderedRsv { get; set; }
        public Nullable<decimal> ActualRemain { get; set; }
        public string Num { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string MatName { get; set; }
        public string GrpName { get; set; }
        public string WhName { get; set; }
        public int WType { get; set; }
        public string DocTypeName { get; set; }
        public string SupplierName { get; set; }
        public System.Guid WaybillListId { get; set; }
    }
}
