//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.WMatTurn = new HashSet<WMatTurn>();
            this.WaybillMove = new HashSet<WaybillMove>();
            this.WaybillMove1 = new HashSet<WaybillMove>();
            this.WayBillMake = new HashSet<WayBillMake>();
            this.DeboningDet = new HashSet<DeboningDet>();
            this.Materials = new HashSet<Materials>();
            this.Materials1 = new HashSet<Materials>();
            this.Materials2 = new HashSet<Materials>();
            this.WaybillDet = new HashSet<WaybillDet>();
            this.ProductionPlanDet = new HashSet<ProductionPlanDet>();
            this.UserAccessWh = new HashSet<UserAccessWh>();
            this.PosRemains = new HashSet<PosRemains>();
            this.ProductionPlans = new HashSet<ProductionPlans>();
            this.ProductionPlans1 = new HashSet<ProductionPlans>();
            this.MatRecDet = new HashSet<MatRecDet>();
        }
    
        public int WId { get; set; }
        public string Name { get; set; }
        public string Addr { get; set; }
        public string Notes { get; set; }
        public int Deleted { get; set; }
        public int Def { get; set; }
        public Nullable<int> RecyclingWarehouse { get; set; }
        public Nullable<int> OpenStoreId { get; set; }
    
        public virtual ICollection<WMatTurn> WMatTurn { get; set; }
        public virtual ICollection<WaybillMove> WaybillMove { get; set; }
        public virtual ICollection<WaybillMove> WaybillMove1 { get; set; }
        public virtual ICollection<WayBillMake> WayBillMake { get; set; }
        public virtual ICollection<DeboningDet> DeboningDet { get; set; }
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<Materials> Materials1 { get; set; }
        public virtual ICollection<Materials> Materials2 { get; set; }
        public virtual ICollection<WaybillDet> WaybillDet { get; set; }
        public virtual ICollection<ProductionPlanDet> ProductionPlanDet { get; set; }
        public virtual ICollection<UserAccessWh> UserAccessWh { get; set; }
        public virtual ICollection<PosRemains> PosRemains { get; set; }
        public virtual ICollection<ProductionPlans> ProductionPlans { get; set; }
        public virtual ICollection<ProductionPlans> ProductionPlans1 { get; set; }
        public virtual ICollection<MatRecDet> MatRecDet { get; set; }
    }
}
