//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAYBILLDETTAXES
    {
        public int POSID { get; set; }
        public int TAXID { get; set; }
        public decimal ONVALUE { get; set; }
    
        public virtual TAXES TAXES { get; set; }
        public virtual WaybillDet WaybillDet { get; set; }
    }
}
