//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaybillMove
    {
        public int WBillId { get; set; }
        public int SourceWid { get; set; }
        public Nullable<int> DestWId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
        public virtual WaybillList WaybillList { get; set; }
        public virtual Kagent Kagent { get; set; }
    }
}
