//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Sklad.SkladData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayBillMake
    {
        public int WbillId { get; set; }
        public int SourceWId { get; set; }
        public Nullable<int> RecId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AmountByRecipe { get; set; }
        public Nullable<int> RecipeCount { get; set; }
    
        public virtual MatRecipe MatRecipe { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual WaybillList WaybillList { get; set; }
        public virtual Kagent Kagent { get; set; }
    }
}
