//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Tranzit.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAREA
    {
        public int SAREAID { get; set; }
        public int PRCLEVELID { get; set; }
        public int CASHPROFILEID { get; set; }
        public Nullable<int> ARTHOTKEYSETID { get; set; }
        public int WAREHOUSEID { get; set; }
        public Nullable<int> PRNSCHEMEID { get; set; }
        public Nullable<int> CURRENCYID { get; set; }
        public string SAREANAME { get; set; }
        public string SAREAADDR { get; set; }
        public Nullable<short> ASKPINCODE { get; set; }
        public string RECEIPTHEADER { get; set; }
        public short DELFLAG { get; set; }
        public string RECEIPTFOOTER { get; set; }
        public int UPDATENUM { get; set; }
        public string RECEIPTFIRSTHEADER { get; set; }
        public string RECEIPTENDFOOTER { get; set; }
    }
}
