//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Tranzit.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Payment
    {
        public string SAREANAME { get; set; }
        public int SAREAID { get; set; }
        public int SYSTEMID { get; set; }
        public int SESSID { get; set; }
        public int SALESNUM { get; set; }
        public string SALESTIME { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string FRECNUM { get; set; }
        public int SRECNUM { get; set; }
        public string SESSSTART { get; set; }
        public string SESSEND { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
    }
}
