//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Tranzit.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sales
    {
        public string SAREANAME { get; set; }
        public int SAREAID { get; set; }
        public int SYSTEMID { get; set; }
        public int SESSID { get; set; }
        public int SALESNUM { get; set; }
        public string SALESTIME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string FRECNUM { get; set; }
        public int SRECNUM { get; set; }
        public Nullable<int> PACKID { get; set; }
        public string UNITNAME { get; set; }
        public string ARTNAME { get; set; }
        public string SESSSTART { get; set; }
        public string SESSEND { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> ARTID { get; set; }
        public int ARTCODE { get; set; }
        public int GRPID { get; set; }
        public string GRPNAME { get; set; }
        public Nullable<System.DateTime> SessionStartDate { get; set; }
    }
}
